# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

CELL_SIZE = 100

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, size: int, mines_cnt: int):
        MainWindow.setObjectName("Minesweeper")
        MainWindow.resize(800, 800)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("Minesweeper")
        
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 40, CELL_SIZE*(size), CELL_SIZE*size))
        self.widget.setObjectName("widget")

        self.gridLayout = QtWidgets.QGridLayout(spacing = 0)
        self.gridLayout.setObjectName("gridLayout")

        self.widget.setLayout(self.gridLayout)

        self.cells: list[QtWidgets.QPushButton] = []
        for i in range(size**2):
            self.cells.append(QtWidgets.QPushButton(self.widget))
            self.cells[-1].setObjectName(f"pushButton{i}")
            self.cells[-1].setFixedSize(CELL_SIZE, CELL_SIZE)
            self.cells[-1].setStyleSheet("border :3px solid ;"
                                         "background-color: gray;")
            self.gridLayout.addWidget(self.cells[i], i//size, i%size, 1, 1)
        
        self.check_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_btn.setObjectName("check_btn")
        self.check_btn.setIcon(QtGui.QIcon("pictures\\shovel.png"))
        self.check_btn.setIconSize(QtCore.QSize(CELL_SIZE, CELL_SIZE))
        self.check_btn.setFixedSize(CELL_SIZE, CELL_SIZE)
        self.check_btn.setGeometry(QtCore.QRect(40 + CELL_SIZE, 6*CELL_SIZE, CELL_SIZE*size, CELL_SIZE*size))

        self.flag_btn = QtWidgets.QPushButton(self.centralwidget)
        self.flag_btn.setObjectName("flag_btn")
        self.flag_btn.setIcon(QtGui.QIcon("pictures\\flag.png"))
        self.flag_btn.setIconSize(QtCore.QSize(CELL_SIZE, CELL_SIZE))
        self.flag_btn.setFixedSize(CELL_SIZE, CELL_SIZE)
        self.flag_btn.setGeometry(QtCore.QRect(40 + (size - 2)*CELL_SIZE, 6*CELL_SIZE, CELL_SIZE*size, CELL_SIZE*size))

        
        MainWindow.setCentralWidget(self.centralwidget)


if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, 5, 5)
    MainWindow.show()
    sys.exit(app.exec_())
